
/* MAIN */

const GITHUB_REPOS_PER_PAGE = 100;
const GITHUB_REPOS_SORT_DIMENSION = 'full_name';
const GITHUB_REPOS_SORT_DIRECTION = 'asc';
const GITHUB_REPOS_TYPE = 'owner';

/* EXPORT */

export {GITHUB_REPOS_PER_PAGE, GITHUB_REPOS_SORT_DIMENSION, GITHUB_REPOS_SORT_DIRECTION, GITHUB_REPOS_TYPE};
